[tool.poetry]
name = "porn-scraper"
version = "1.0.0"
description = ""
authors = ["mhaii <mhaii@pukenicorn.com>"]
readme = "README.md"
#packages = [{include = "app"}] # Not gonna build for dist

[tool.poetry.dependencies]
python = "^3.8"
javscraper = "^1.1.8"
fastapi = "^0.85.0"
uvicorn = "^0.18.3"

[tool.poetry.group.dev.dependencies]
taskipy = "^1.10.3"
pyyaml = "^6.0"

[tool.taskipy.tasks]
# poetry run task xxxxx
generate = "python -m openapi.generate"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
