[tool.poetry]
name = "porn-scraper"
version = "1.0.0"
description = ""
authors = ["mhaii <mhaii@pukenicorn.com>"]
readme = "README.md"
#packages = [{include = "app"}] # Not gonna build for dist

[tool.poetry.dependencies]
python = "^3.10"
javscraper = "^1.1.8"
fastapi = "^0.85.1"
uvicorn = "^0.19.0"
taskipy = "^1.10.3"
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]

[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"


[tool.taskipy.tasks]
# poetry run task xxxxx
"generate:spec" = "python -m tasks.generate-spec"
"generate:client-ts-axios" = "make genc-axios"
"generate:client-ts-nestjs" = "make genc-nestjs"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
