[tool.poetry]
name = "porn-scraper"
version = "1.0.0"
description = ""
authors = ["mhaii <mhaii@pukenicorn.com>"]
readme = "README.md"
#packages = [{include = "app"}] # Not gonna build for dist

[tool.poetry.dependencies]
python = "^3.8"
javscraper = "^1.1.8"
fastapi = "^0.85.1"
uvicorn = "^0.19.0"

[tool.poetry.group.dev.dependencies]
taskipy = "^1.10.3"
pyyaml = "^6.0"
openapi-generator-cli = "^4.3.1"

[tool.taskipy.tasks]
# poetry run task xxxxx
"generate:spec" = "python -m openapi.generate"
"generate:client-ts-axios" = """
    openapi-generator generate \
        -g typescript-axios \
        --additional-properties=supportsES6=true \
        -i ./openapi/openapi.yml \
        -o ./generated/ts/axios
    """
"generate:client-ts-nestjs" = """
    openapi-generator generate \
        -g typescript-nestjs \
        --additional-properties=serviceSuffix=ScraperService,supportsES6=true \
        -i ./openapi/openapi.yml \
        -o ./generated/ts/nestjs
    """


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
