components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    JAVResult:
      properties:
        actresses:
          items:
            type: string
          title: Actresses
          type: array
        code:
          title: Code
          type: string
        description:
          title: Description
          type: string
        genres:
          items:
            type: string
          title: Genres
          type: array
        image:
          title: Image
          type: string
        name:
          title: Name
          type: string
        release_date:
          format: date-time
          title: Release Date
          type: string
        sample_video:
          title: Sample Video
          type: string
        score:
          anyOf:
          - type: integer
          - type: number
          default: 0
          title: Score
        studio:
          title: Studio
          type: string
      required:
      - name
      - code
      - studio
      - image
      - actresses
      - genres
      - release_date
      title: JAVResult
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /jav/{code}:
    get:
      operationId: lookup_jav__code__get
      parameters:
      - in: path
        name: code
        required: true
        schema:
          title: Code
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JAVResult'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Lookup
      tags:
      - jav
