name: Build image to ghcr

on:
  push:
#    branches:
#      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: "Build to Github Container Registry"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Detect changes
        uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            build:
              - ./!(**.md)
      - name: Docker Metadata
        uses: docker/metadata-action@v4.0.1
        id: meta
        if: steps.filter.outputs.build == 'true' || ( github.event_name == 'release' && github.event.action == 'published' )
        with:
          images: mhaii/porn-scraper
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
        if: steps.filter.outputs.build == 'true' || ( github.event_name == 'release' && github.event.action == 'published' )
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2.0.0
        if: steps.filter.outputs.build == 'true' || ( github.event_name == 'release' && github.event.action == 'published' )
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        if: ( steps.filter.outputs.build == 'true' && github.event_name != 'pull_request' ) || ( github.event_name == 'release' && github.event.action == 'published' )
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3.1.1
        if: steps.filter.outputs.build == 'true' || ( github.event_name == 'release' && github.event.action == 'published' )
        with:
#          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          platforms: linux/amd64
          tags: gchr.io/${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}