name: Test, build and publish packages

permissions:
  contents: read
  packages: write

concurrency:
  group: publish-${{ github.event_name }}
  cancel-in-progress: true

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Version to the publish package
        type: string
        required: true

jobs:
  test:
    name: Run test
    uses: pukenicorn/gh-workflows/.github/workflows/test.yml@main
    with:
      language: python

  publish-docker:
    name: Build and publish docker image
    needs: [test]
    uses: pukenicorn/gh-workflows/.github/workflows/publish-docker.yml@main
    with:
      registry: ghcr.io
      ignore-file-changes: ${{ (github.event_name == 'release' && github.event.action == 'published') || github.event_name == 'workflow_dispatch' }}
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}

  publish-client-ts-axios:
    name: Build and publish typescript axios client
    needs: [test]
    uses: pukenicorn/gh-workflows/.github/workflows/publish-pkg.yml@main
    with:
      base-language: python
      package-language: node
      package-language-cache: none
      package-path: ./generated
      post-setup-command: generate:spec
      package-name: "@${{ github.repository }}-client"
      package-registry: https://npm.pkg.github.com
      package-version: ${{ github.event.release.tag_name || inputs.version }}
    if: github.event_name == 'release' && github.event.action == 'published'
