name: Test and check for dependabot

permissions:
  pull-requests: write
  contents: write

concurrency:
  group: pr-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      pr-number:
        description: ID of PR to be run against
        type: string
        required: true


jobs:
  test:
    uses: pukenicorn/gh-workflows/.github/workflows/test.yml@main
    with:
      language: python

  dependabot:
    needs: [test]
    uses: pukenicorn/gh-workflows/.github/workflows/dependabot.yml@main
    with:
      pr-number: ${{ inputs.pr_number }}
    if: github.event_name == 'workflow_dispatch'
